# Generated by Django 4.2.21 on 2025-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_status', models.CharField(choices=[('not full', 'Not Full'), ('full', 'Full')], default='not full', max_length=20)),
                ('non_bio_status', models.CharField(choices=[('not full', 'Not Full'), ('full', 'Full')], default='not full', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
